-- Calisthenics Skill Tree — Supabase schema (all-DB model: every skill lives here)
-- Run this in the Supabase Dashboard → SQL Editor.

-- ---------- tables ----------

-- one row per authenticated user
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  created_at timestamptz not null default now()
);

-- ALL skills (admin-managed; single source of truth — no built-ins in code)
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'other',
  difficulty text not null default 'Beginner',
  summary text not null default '',
  icon text not null default '',          -- public Storage URL (no more base64)
  video_id text not null default '',
  position_left int not null default 0,
  position_top int not null default 0,
  prerequisites bigint[] not null default '{}',
  instructions text[] not null default '{}',
  mistakes text[] not null default '{}',
  tips text[] not null default '{}',
  created_at timestamptz not null default now()
);

-- which skills a user has marked complete
create table if not exists public.completions (
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, exercise_id)
);

-- ---------- admin check (from the signed-in user's email in the JWT) ----------
create or replace function public.is_admin()
returns boolean language sql stable as $$
  select coalesce(auth.jwt() ->> 'email', '') = 'septrealdakheel@gmail.com'
$$;

-- ---------- auto-create a profile on signup ----------
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- row level security ----------
alter table public.profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.completions enable row level security;

-- profiles: each user reads/writes only their own row
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id);

-- exercises: anyone can read; only the admin can write
create policy "exercises_select_all" on public.exercises for select using (true);
create policy "exercises_admin_write" on public.exercises for all
  using (public.is_admin()) with check (public.is_admin());

-- completions: each user manages only their own
create policy "completions_select_own" on public.completions for select using (auth.uid() = user_id);
create policy "completions_insert_own" on public.completions for insert with check (auth.uid() = user_id);
create policy "completions_delete_own" on public.completions for delete using (auth.uid() = user_id);

-- ---------- table privileges (RLS filters rows; these allow the roles in) ----------
grant usage on schema public to anon, authenticated;
grant select on public.exercises to anon, authenticated;
grant insert, update, delete on public.exercises to authenticated;   -- RLS still limits writes to admin
grant select, insert, update, delete on public.completions to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;

-- ---------- storage: public bucket for exercise images ----------
insert into storage.buckets (id, name, public)
values ('exercise-images', 'exercise-images', true)
on conflict (id) do nothing;

create policy "exercise_images_public_read" on storage.objects
  for select using (bucket_id = 'exercise-images');
create policy "exercise_images_admin_insert" on storage.objects
  for insert with check (bucket_id = 'exercise-images' and public.is_admin());
create policy "exercise_images_admin_update" on storage.objects
  for update using (bucket_id = 'exercise-images' and public.is_admin());
create policy "exercise_images_admin_delete" on storage.objects
  for delete using (bucket_id = 'exercise-images' and public.is_admin());
